#!/usr/bin/env python3
"""Single-pass replacement:
1. Insert the layout-constants block after `Private Const RESULT_COL_SECTION As Long = 4`.
2. Replace the existing CreateMonthlyPage body with a constant-driven version that
   preserves every literal value (verified by tools/verify_geometry.py)."""
from pathlib import Path

src = Path("CreateOrder.xlsm.modules/frmEnrollmentWizard.frm")
data = src.read_bytes()

# --- 1. Constants block --------------------------------------------------
old_anchor_1 = (
    "Private Const RESULT_COL_SECTION As Long = 4\r\n"
    "\r\n"
    "Private mpWizard As Object\r\n"
).encode("cp1251")

new_anchor_1 = (
    "Private Const RESULT_COL_SECTION As Long = 4\r\n"
    "\r\n"
    "' ----- Layout constants for the monthly payments page (CreateMonthlyPage) -----\r\n"
    "' Geometry is collected here so the layout can be tuned without reading the body of CreateMonthlyPage.\r\n"
    "Private Const FRA727_LEFT As Single = 12\r\n"
    "Private Const FRA727_TOP As Single = 52\r\n"
    "Private Const FRA727_WIDTH As Single = 744\r\n"
    "Private Const FRA727_HEIGHT As Single = 168\r\n"
    "\r\n"
    "Private Const FRA430_LEFT As Single = 12\r\n"
    "Private Const FRA430_TOP As Single = 232\r\n"
    "Private Const FRA430_WIDTH As Single = 744\r\n"
    "Private Const FRA430_HEIGHT As Single = 174\r\n"
    "\r\n"
    "' Standard control sizes used across the monthly page.\r\n"
    "Private Const CTRL_PERCENT_WIDTH As Single = 52\r\n"
    "Private Const CTRL_PARAM_WIDTH As Single = 136\r\n"
    "Private Const CTRL_PARAM_ACHIEVEMENT_WIDTH As Single = 174\r\n"
    "Private Const CTRL_DATE_WIDTH As Single = 92\r\n"
    "Private Const CTRL_DOC_WIDTH As Single = 192\r\n"
    "Private Const CTRL_PREMIUM_WIDTH As Single = 82\r\n"
    "Private Const CTRL_PREMIUM_START_WIDTH As Single = 82\r\n"
    "Private Const CTRL_PREMIUM_END_WIDTH As Single = 82\r\n"
    "Private Const CTRL_HEIGHT_DEFAULT As Single = 18\r\n"
    "Private Const CTRL_LBL_TARIFF_WIDTH As Single = 246\r\n"
    "\r\n"
    "' Row baselines inside fraOrder727.\r\n"
    "' Each row carries a checkbox (top1) and adjacent percent textbox (top2). The\r\n"
    "' textbox is placed 4 points above the checkbox so their visible centres align.\r\n"
    "Private Const FRA727_ROW1_CHK_TOP As Single = 18       ' std_duty / std_special checkboxes\r\n"
    "Private Const FRA727_ROW1_TXT_TOP As Single = 14       ' std_duty% / std_special% textboxes\r\n"
    "Private Const FRA727_ROW2_CHK_TOP As Single = 80       ' secrecy / class checkboxes (\"Вкл\")\r\n"
    "Private Const FRA727_ROW2_TXT_TOP As Single = 62       ' secrecy/class param combo and % textbox\r\n"
    "Private Const FRA727_ROW3_CHK_TOP As Single = 114      ' premium checkbox (rendered slightly lower than textboxes)\r\n"
    "Private Const FRA727_ROW3_TXT_TOP As Single = 110      ' premium% / premium dates\r\n"
    "Private Const FRA727_COL_LEFT As Single = 18\r\n"
    "Private Const FRA727_COL_LEFT_PERCENT As Single = 178\r\n"
    "Private Const FRA727_COL_RIGHT As Single = 386\r\n"
    "Private Const FRA727_COL_RIGHT_PERCENT As Single = 514\r\n"
    "Private Const FRA727_COL_RIGHT_CHK As Single = 530\r\n"
    "Private Const FRA727_COL_RIGHT_CLASS_PERCENT As Single = 578\r\n"
    "\r\n"
    "' Row baselines inside fraOrder430.\r\n"
    "Private Const FRA430_ROW1_CHK_TOP As Single = 18       ' contract430 checkbox / contract430% textbox\r\n"
    "Private Const FRA430_ROW1_TXT_TOP As Single = 14       ' contract430% textbox (rendered above the checkbox)\r\n"
    "Private Const FRA430_ROW2_LBL_TOP As Single = 54       ' 1-4 tariff label / tariff% textbox\r\n"
    "Private Const FRA430_ROW2_TXT_TOP As Single = 50       ' tariff% textbox\r\n"
    "Private Const FRA430_ROW3_CHK_TOP As Single = 102      ' fizo / achievement checkboxes (\"Вкл\")\r\n"
    "Private Const FRA430_ROW3_TXT_TOP As Single = 84       ' fizo/achievement param combo and % textbox\r\n"
    "Private Const FRA430_ROW4_TOP As Single = 126          ' medal award date / order row\r\n"
    "Private Const FRA430_COL_LEFT As Single = 18\r\n"
    "Private Const FRA430_COL_LEFT_PERCENT As Single = 168\r\n"
    "Private Const FRA430_COL_LEFT_TARIFF_PERCENT As Single = 274\r\n"
    "Private Const FRA430_COL_LEFT_FIZO_PERCENT As Single = 210\r\n"
    "Private Const FRA430_COL_RIGHT As Single = 386\r\n"
    "Private Const FRA430_COL_RIGHT_CHK As Single = 568\r\n"
    "Private Const FRA430_COL_RIGHT_AMOUNT As Single = 616\r\n"
    "Private Const FRA430_COL_RIGHT_AMOUNT_WIDTH As Single = 70\r\n"
    "Private Const FRA430_COL_DATE As Single = 386\r\n"
    "Private Const FRA430_COL_DOC As Single = 494\r\n"
    "\r\n"
    "Private mpWizard As Object\r\n"
).encode("cp1251")

assert old_anchor_1 in data, "anchor 1 not found (RESULT_COL_SECTION ... mpWizard)"
data = data.replace(old_anchor_1, new_anchor_1, 1)
print("Constants block inserted.")

# --- 2. CreateMonthlyPage replacement -----------------------------------
old_cpm = (
    "Private Sub CreateMonthlyPage()\r\n"
    "    Set chkPreferential = AddPageCheckBoxT(pgMonthly, \"enrollment.field.preferential_enabled\", \"Льготная выслуга\", 24, 18)\r\n"
    "    chkPreferential.Width = 140\r\n"
    "    Set txtPreferentialCoeff = AddPageTextBoxT(pgMonthly, \"enrollment.field.preferential_coeff\", \"Коэффициент\", 176, 14, 56)\r\n"
    "    AddPageSectionLabel pgMonthly, \"Льготная выслуга применяется отдельно и включена по умолчанию\", 250, 18, 420\r\n"
    "\r\n"
    "    Set fraOrder727 = AddPageFrame(pgMonthly, \"fraOrder727\", \"Приказ МО РФ № 727 — ежемесячные выплаты\", 12, 52, 744, 168)\r\n"
    "    Set chkStdDuty = AddPageCheckBoxT(fraOrder727, \"enrollment.field.std_duty\", \"Надбавка по должности\", 18, 18)\r\n"
    "    chkStdDuty.Width = 150\r\n"
    "    Set txtStdDutyPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", 178, 14, 52)\r\n"
    "    Set chkStdSpecial = AddPageCheckBoxT(fraOrder727, \"enrollment.field.std_special\", \"Особые условия\", 386, 18)\r\n"
    "    chkStdSpecial.Width = 120\r\n"
    "    Set txtStdSpecialPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", 514, 14, 52)\r\n"
    "\r\n"
    "    Set txtSecrecyParam = AddPageComboBoxT(fraOrder727, \"enrollment.field.secrecy_param\", \"Секретность\", 18, 62, 136)\r\n"
    "    Set chkSecrecy = AddPageCheckBoxT(fraOrder727, \"common.enabled_short\", \"Вкл\", 162, 80)\r\n"
    "    chkSecrecy.Width = 40\r\n"
    "    Set txtSecrecyPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", 210, 62, 52, 18, False, True)\r\n"
    "    Set txtClassParam = AddPageComboBoxT(fraOrder727, \"enrollment.field.class_param\", \"Классность\", 386, 62, 136)\r\n"
    "    Set chkClass = AddPageCheckBoxT(fraOrder727, \"common.enabled_short\", \"Вкл\", 530, 80)\r\n"
    "    chkClass.Width = 40\r\n"
    "    Set txtClassPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", 578, 62, 52, 18, False, True)\r\n"
    "\r\n"
    "    Set chkPremium = AddPageCheckBoxT(fraOrder727, \"enrollment.field.premium\", \"Премия\", 18, 114)\r\n"
    "    chkPremium.Width = 82\r\n"
    "    Set txtPremiumPercent = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_percent\", \"%\", 108, 110, 52)\r\n"
    "    Set txtPremiumStart = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_start\", \"Начало\", 178, 110, 82)\r\n"
    "    Set txtPremiumEnd = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_end\", \"Окончание\", 278, 110, 82)\r\n"
    "\r\n"
    "    Set fraOrder430 = AddPageFrame(pgMonthly, \"fraOrder430\", \"Приказ МО РФ № 430дсп — индивидуальные основания\", 12, 232, 744, 174)\r\n"
    "    Set chkStdContract430 = AddPageCheckBoxT(fraOrder430, \"enrollment.field.std_contract430\", \"Контракт / 430дсп\", 18, 18)\r\n"
    "    chkStdContract430.Width = 142\r\n"
    "    Set txtStdContract430Percent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", 168, 14, 52)\r\n"
    "    Set chkStdTariff = AddPageCheckBoxT(fraOrder430, \"enrollment.field.std_tariff\", \"\", 12, 54)\r\n"
    "    chkStdTariff.Visible = False\r\n"
    "    Set lblTariffAllowanceState = AddLabelToPage(fraOrder430, \"1–4 тариф: определяется по выбранному разряду\", 18, 54, 246)\r\n"
    "    Set txtStdTariffPercent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", 274, 50, 52, 18, False, True)\r\n"
    "\r\n"
    "    Set txtFizoParam = AddPageComboBoxT(fraOrder430, \"enrollment.field.fizo_param\", \"ФИЗО\", 18, 84, 136)\r\n"
    "    Set chkFizo = AddPageCheckBoxT(fraOrder430, \"common.enabled_short\", \"Вкл\", 162, 102)\r\n"
    "    chkFizo.Width = 40\r\n"
    "    Set txtFizoPercent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", 210, 84, 52, 18, False, True)\r\n"
    "    Set txtAchievementParam = AddPageComboBoxT(fraOrder430, \"enrollment.field.achievement_param\", \"Особые достижения / медаль\", 386, 84, 174)\r\n"
    "    Set chkAchievement = AddPageCheckBoxT(fraOrder430, \"common.enabled_short\", \"Вкл\", 568, 102)\r\n"
    "    chkAchievement.Width = 40\r\n"
    "    Set txtAchievementAmount = AddPageTextBoxT(fraOrder430, \"enrollment.field.achievement_amount\", \"% / сумма\", 616, 84, 70, 18, False, True)\r\n"
    "    Set txtAchievementAwardDate = AddPageTextBoxT(fraOrder430, \"common.date\", \"Дата приказа\", 386, 126, 92)\r\n"
    "    Set txtAchievementDocumentReference = AddPageTextBoxT(fraOrder430, \"enrollment.field.order_number\", \"Номер приказа\", 494, 126, 192)\r\n"
    "\r\n"
    "    ConfigureScrollablePage pgMonthly, 0, True\r\n"
    "End Sub\r\n"
).encode("cp1251")

new_cpm = (
    "Private Sub CreateMonthlyPage()\r\n"
    "    ' Geometry lives in the layout constants at the top of this module.\r\n"
    "    Set chkPreferential = AddPageCheckBoxT(pgMonthly, \"enrollment.field.preferential_enabled\", \"Льготная выслуга\", 24, 18)\r\n"
    "    chkPreferential.Width = 140\r\n"
    "    Set txtPreferentialCoeff = AddPageTextBoxT(pgMonthly, \"enrollment.field.preferential_coeff\", \"Коэффициент\", 176, 14, 56)\r\n"
    "    AddPageSectionLabel pgMonthly, \"Льготная выслуга применяется отдельно и включена по умолчанию\", 250, 18, 420\r\n"
    "\r\n"
    "    Set fraOrder727 = AddPageFrame(pgMonthly, \"fraOrder727\", \"Приказ МО РФ № 727 — ежемесячные выплаты\", FRA727_LEFT, FRA727_TOP, FRA727_WIDTH, FRA727_HEIGHT)\r\n"
    "    Set chkStdDuty = AddPageCheckBoxT(fraOrder727, \"enrollment.field.std_duty\", \"Надбавка по должности\", FRA727_COL_LEFT, FRA727_ROW1_CHK_TOP)\r\n"
    "    chkStdDuty.Width = 150\r\n"
    "    Set txtStdDutyPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", FRA727_COL_LEFT_PERCENT, FRA727_ROW1_TXT_TOP, CTRL_PERCENT_WIDTH)\r\n"
    "    Set chkStdSpecial = AddPageCheckBoxT(fraOrder727, \"enrollment.field.std_special\", \"Особые условия\", FRA727_COL_RIGHT, FRA727_ROW1_CHK_TOP)\r\n"
    "    chkStdSpecial.Width = 120\r\n"
    "    Set txtStdSpecialPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", FRA727_COL_RIGHT_PERCENT, FRA727_ROW1_TXT_TOP, CTRL_PERCENT_WIDTH)\r\n"
    "\r\n"
    "    Set txtSecrecyParam = AddPageComboBoxT(fraOrder727, \"enrollment.field.secrecy_param\", \"Секретность\", FRA727_COL_LEFT, FRA727_ROW2_TXT_TOP, CTRL_PARAM_WIDTH)\r\n"
    "    Set chkSecrecy = AddPageCheckBoxT(fraOrder727, \"common.enabled_short\", \"Вкл\", 162, FRA727_ROW2_CHK_TOP)\r\n"
    "    chkSecrecy.Width = 40\r\n"
    "    Set txtSecrecyPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", 210, FRA727_ROW2_TXT_TOP, CTRL_PERCENT_WIDTH, CTRL_HEIGHT_DEFAULT, False, True)\r\n"
    "    Set txtClassParam = AddPageComboBoxT(fraOrder727, \"enrollment.field.class_param\", \"Классность\", FRA727_COL_RIGHT, FRA727_ROW2_TXT_TOP, CTRL_PARAM_WIDTH)\r\n"
    "    Set chkClass = AddPageCheckBoxT(fraOrder727, \"common.enabled_short\", \"Вкл\", FRA727_COL_RIGHT_CHK, FRA727_ROW2_CHK_TOP)\r\n"
    "    chkClass.Width = 40\r\n"
    "    Set txtClassPercent = AddPageTextBoxT(fraOrder727, \"common.percent\", \"%\", FRA727_COL_RIGHT_CLASS_PERCENT, FRA727_ROW2_TXT_TOP, CTRL_PERCENT_WIDTH, CTRL_HEIGHT_DEFAULT, False, True)\r\n"
    "\r\n"
    "    Set chkPremium = AddPageCheckBoxT(fraOrder727, \"enrollment.field.premium\", \"Премия\", FRA727_COL_LEFT, FRA727_ROW3_CHK_TOP)\r\n"
    "    chkPremium.Width = CTRL_PREMIUM_WIDTH\r\n"
    "    Set txtPremiumPercent = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_percent\", \"%\", 108, FRA727_ROW3_TXT_TOP, CTRL_PERCENT_WIDTH)\r\n"
    "    Set txtPremiumStart = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_start\", \"Начало\", 178, FRA727_ROW3_TXT_TOP, CTRL_PREMIUM_START_WIDTH)\r\n"
    "    Set txtPremiumEnd = AddPageTextBoxT(fraOrder727, \"enrollment.field.premium_end\", \"Окончание\", 278, FRA727_ROW3_TXT_TOP, CTRL_PREMIUM_END_WIDTH)\r\n"
    "\r\n"
    "    Set fraOrder430 = AddPageFrame(pgMonthly, \"fraOrder430\", \"Приказ МО РФ № 430дсп — индивидуальные основания\", FRA430_LEFT, FRA430_TOP, FRA430_WIDTH, FRA430_HEIGHT)\r\n"
    "    Set chkStdContract430 = AddPageCheckBoxT(fraOrder430, \"enrollment.field.std_contract430\", \"Контракт / 430дсп\", FRA430_COL_LEFT, FRA430_ROW1_CHK_TOP)\r\n"
    "    chkStdContract430.Width = 142\r\n"
    "    Set txtStdContract430Percent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", FRA430_COL_LEFT_PERCENT, FRA430_ROW1_TXT_TOP, CTRL_PERCENT_WIDTH)\r\n"
    "    Set chkStdTariff = AddPageCheckBoxT(fraOrder430, \"enrollment.field.std_tariff\", \"\", 12, 54)\r\n"
    "    chkStdTariff.Visible = False\r\n"
    "    Set lblTariffAllowanceState = AddLabelToPage(fraOrder430, \"1–4 тариф: определяется по выбранному разряду\", FRA430_COL_LEFT, FRA430_ROW2_LBL_TOP, CTRL_LBL_TARIFF_WIDTH)\r\n"
    "    Set txtStdTariffPercent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", FRA430_COL_LEFT_TARIFF_PERCENT, FRA430_ROW2_TXT_TOP, CTRL_PERCENT_WIDTH, CTRL_HEIGHT_DEFAULT, False, True)\r\n"
    "\r\n"
    "    Set txtFizoParam = AddPageComboBoxT(fraOrder430, \"enrollment.field.fizo_param\", \"ФИЗО\", FRA430_COL_LEFT, FRA430_ROW3_TXT_TOP, CTRL_PARAM_WIDTH)\r\n"
    "    Set chkFizo = AddPageCheckBoxT(fraOrder430, \"common.enabled_short\", \"Вкл\", 162, FRA430_ROW3_CHK_TOP)\r\n"
    "    chkFizo.Width = 40\r\n"
    "    Set txtFizoPercent = AddPageTextBoxT(fraOrder430, \"common.percent\", \"%\", FRA430_COL_LEFT_FIZO_PERCENT, FRA430_ROW3_TXT_TOP, CTRL_PERCENT_WIDTH, CTRL_HEIGHT_DEFAULT, False, True)\r\n"
    "    Set txtAchievementParam = AddPageComboBoxT(fraOrder430, \"enrollment.field.achievement_param\", \"Особые достижения / медаль\", FRA430_COL_RIGHT, FRA430_ROW3_TXT_TOP, CTRL_PARAM_ACHIEVEMENT_WIDTH)\r\n"
    "    Set chkAchievement = AddPageCheckBoxT(fraOrder430, \"common.enabled_short\", \"Вкл\", FRA430_COL_RIGHT_CHK, FRA430_ROW3_CHK_TOP)\r\n"
    "    chkAchievement.Width = 40\r\n"
    "    Set txtAchievementAmount = AddPageTextBoxT(fraOrder430, \"enrollment.field.achievement_amount\", \"% / сумма\", FRA430_COL_RIGHT_AMOUNT, FRA430_ROW3_TXT_TOP, FRA430_COL_RIGHT_AMOUNT_WIDTH, CTRL_HEIGHT_DEFAULT, False, True)\r\n"
    "    Set txtAchievementAwardDate = AddPageTextBoxT(fraOrder430, \"common.date\", \"Дата приказа\", FRA430_COL_DATE, FRA430_ROW4_TOP, CTRL_DATE_WIDTH)\r\n"
    "    Set txtAchievementDocumentReference = AddPageTextBoxT(fraOrder430, \"enrollment.field.order_number\", \"Номер приказа\", FRA430_COL_DOC, FRA430_ROW4_TOP, CTRL_DOC_WIDTH)\r\n"
    "\r\n"
    "    ConfigureScrollablePage pgMonthly, 0, True\r\n"
    "End Sub\r\n"
).encode("cp1251")

assert old_cpm in data, "old CreateMonthlyPage not found"
data = data.replace(old_cpm, new_cpm, 1)
print("CreateMonthlyPage replaced with constant-driven version.")

src.write_bytes(data)
print("Final size:", len(data))